### ISSUE TITLE
Rename project to RoboTK

### ISSUE THREAD

**Issue by mikestephens** [hash-gaming/robotk#16]
RoboTK is a much better name, lets rename this bot.

# Tasks
- [x] Rename Github Repo
- [ ] Rename bot in code
- [x] Rename bot in Readme
- [ ] Rename bot in slack
